[package]
name = "bestcrow"
version = "0.1.0"
edition = "2021"
description = "Milestone crowdfunding escrow for Solana"

[lib]
crate-type = ["cdylib", "lib"]
name = "bestcrow"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "=1.1.2", features = ["init-if-needed"] }
anchor-spl = { version = "=1.1.2", features = ["associated_token", "token"] }
